extends Node
class_name CardDatabase

static var card_database = {
	"copper_coin": {
		"card": preload("res://Images/currency_card.png"),
		"sprite": preload("res://Images/copper_coin.png"),
		"card_type": "currency",
		"display_name": "Copper Coin",
		"value": 1,
		"rarity": "silver",
		"description": "A dull copper coin."
	},
	"silver_coin": {
		"card": preload("res://Images/currency_card.png"),
		"sprite": preload("res://Images/silver_coin.png"),
		"card_type": "currency",
		"display_name": "Silver Coin",
		"value": 10,
		"rarity": "silver",
		"description": "A silver coin. Worth 10 copper coins."
	},
	"gold_coin": {
		"card": preload("res://Images/currency_card.png"),
		"sprite": preload("res://Images/gold_coin.png"),
		"card_type": "currency",
		"display_name": "Gold Coin",
		"value": 100,
		"rarity": "gold",
		"description": "A shiny gold coin. Worth 10 silver coins."
	},
	"plains_card_pack": {
		"card": preload("res://Images/plains_card_pack.png"),
		"sprite": preload("res://Images/blank.png"),
		"card_type": "card_pack",
		"display_name": "",
		"value": 10,
		"rarity": "silver",
		"description": "The plains card pack. The starting location pack.",
		"loot_table": [
			{"subtype": "plains", "weight": 10},
			{"subtype": "plant_fiber", "weight": 45},
			{"subtype": "wheat", "weight": 15},
			{"subtype": "soil", "weight": 20},
			{"subtype": "horse", "weight": 3},
			{"subtype": "cow", "weight": 4},
			{"subtype": "rabbit", "weight": 2},
			{"subtype": "chicken", "weight": 1},
		]
	},
	"forest_card_pack": {
		"card": preload("res://Images/forest_card_pack.png"),
		"sprite": preload("res://Images/blank.png"),
		"card_type": "card_pack",
		"display_name": "",
		"value": 10,
		"rarity": "silver",
		"description": "The forest card pack.",
		"loot_table": [
			{"subtype": "forest", "weight": 10},
			{"subtype": "tree", "weight": 15},
			{"subtype": "wood", "weight": 65},
			{"subtype": "horse", "weight": 2},
			{"subtype": "cow", "weight": 1},
			{"subtype": "rabbit", "weight": 4},
			{"subtype": "chicken", "weight": 3},
		]
	},
	"mountain_card_pack": {
		"card": preload("res://Images/mountain_card_pack.png"),
		"sprite": preload("res://Images/blank.png"),
		"card_type": "card_pack",
		"display_name": "",
		"value": 10,
		"rarity": "silver",
		"description": "The mountain card pack.",
		"loot_table": [
			{"subtype": "mountain", "weight": 10},
			{"subtype": "rock", "weight": 15},
			{"subtype": "iron_deposit", "weight": 4},
			{"subtype": "copper_deposit", "weight": 4},
			{"subtype": "gold_deposit", "weight": 2},
			{"subtype": "stone", "weight": 60},
			{"subtype": "horse", "weight": 2},
			{"subtype": "cow", "weight": 1},
			{"subtype": "rabbit", "weight": 1},
			{"subtype": "chicken", "weight": 1},
		]
	},
	"plains": {
		"card": preload("res://Images/location_card.png"),
		"sprite": preload("res://Images/plains.png"),
		"card_type": "location",
		"display_name": "Plains",
		"value": 5,
	},
	"forest": {
		"card": preload("res://Images/location_card.png"),
		"sprite": preload("res://Images/forest.png"),
		"card_type": "location",
		"display_name": "Forest",
		"value": 5,
	},
	"mountain": {
		"card": preload("res://Images/location_card.png"),
		"sprite": preload("res://Images/mountain.png"),
		"card_type": "location",
		"display_name": "Mountain",
		"value": 5,
	},
	"cave": {
		"card": preload("res://Images/location_card.png"),
		"sprite": preload("res://Images/cave.png"),
		"card_type": "location",
		"display_name": "Cave",
		"value": 5,
	},
	"aquifer": {
		"card": preload("res://Images/location_card.png"),
		"sprite": preload("res://Images/aquifer.png"),
		"card_type": "location",
		"display_name": "Aquifer",
		"value": 5,
		"description": "A large body of water underground.",
	},
	"tree": {
		"card": preload("res://Images/resource_card.png"),
		"sprite": preload("res://Images/tree.png"),
		"card_type": "resource",
		"display_name": "Tree",
		"value": 0,
	},
	"rock": {
		"card": preload("res://Images/resource_card.png"),
		"sprite": preload("res://Images/rock.png"),
		"card_type": "resource",
		"display_name": "Rock",
		"value": 0,
	},
	"iron_deposit": {
		"card": preload("res://Images/resource_card.png"),
		"sprite": preload("res://Images/iron_deposit.png"),
		"card_type": "resource",
		"display_name": "Iron Deposit",
		"value": 0,
	},
	"copper_deposit": {
		"card": preload("res://Images/resource_card.png"),
		"sprite": preload("res://Images/copper_deposit.png"),
		"card_type": "resource",
		"display_name": "Copper Deposit",
		"value": 0,
	},
	"gold_deposit": {
		"card": preload("res://Images/resource_card.png"),
		"sprite": preload("res://Images/gold_deposit.png"),
		"card_type": "resource",
		"display_name": "Gold Deposit",
		"value": 0,
	},
	"soil": { 
		"card": preload("res://Images/resource_card.png"),
		"sprite": preload("res://Images/soil.png"),
		"card_type": "material",
		"display_name": "Soil",
		"value": 0,
	},
	"stone": { 
		"card": preload("res://Images/material_card.png"),
		"sprite": preload("res://Images/stone.png"),
		"card_type": "material",
		"display_name": "Stone",
		"value": 1,
	},
	"wood": {
		"card": preload("res://Images/material_card.png"),
		"sprite": preload("res://Images/wood.png"),
		"card_type": "material",
		"display_name": "Wood",
		"value": 1,
	},
	"water": {
		"card": preload("res://Images/material_card.png"),
		"sprite": preload("res://Images/water.png"),
		"card_type": "material",
		"display_name": "Water",
		"value": 0,
	},
	"plant_fiber": {
		"card": preload("res://Images/material_card.png"),
		"sprite": preload("res://Images/plant_fiber.png"),
		"card_type": "material",
		"display_name": "Plant Fiber",
		"value": 1,
	},
	"wheat": {
		"card": preload("res://Images/material_card.png"),
		"sprite": preload("res://Images/wheat.png"),
		"card_type": "material",
		"display_name": "Wheat",
		"value": 1,
	},
	"rope": {
		"card": preload("res://Images/material_card.png"),
		"sprite": preload("res://Images/rope.png"),
		"card_type": "material",
		"display_name": "Rope",
		"value": 4,
	},
	"leather": {
		"card": preload("res://Images/material_card.png"),
		"sprite": preload("res://Images/leather.png"),
		"card_type": "material",
		"display_name": "Leather",
		"value": 1,
	},
	"iron_ore": {
		"card": preload("res://Images/material_card.png"),
		"sprite": preload("res://Images/iron_ore.png"),
		"card_type": "material",
		"display_name": "Iron Ore",
		"value": 1,
	},
	"copper_ore": {
		"card": preload("res://Images/material_card.png"),
		"sprite": preload("res://Images/copper_ore.png"),
		"card_type": "material",
		"display_name": "Copper Ore",
		"value": 1,
	},
	"gold_ore": {
		"card": preload("res://Images/material_card.png"),
		"sprite": preload("res://Images/gold_ore.png"),
		"card_type": "material",
		"display_name": "Gold Ore",
		"value": 1,
	},
	"iron_ingot": {
		"card": preload("res://Images/material_card.png"),
		"sprite": preload("res://Images/iron_ingot.png"),
		"card_type": "material",
		"display_name": "Iron Ingot",
		"value": 4,
		"rarity": "silver",
	},
	"copper_ingot": {
		"card": preload("res://Images/material_card.png"),
		"sprite": preload("res://Images/copper_ingot.png"),
		"card_type": "material",
		"display_name": "Copper Ingot",
		"value": 4,
		"rarity": "silver",
	},
	"gold_ingot": {
		"card": preload("res://Images/material_card.png"),
		"sprite": preload("res://Images/gold_ingot.png"),
		"card_type": "material",
		"display_name": "Gold Ingot",
		"value": 5,
		"rarity": "gold",
	},
	"plank": {
		"card": preload("res://Images/material_card.png"),
		"sprite": preload("res://Images/plank.png"),
		"card_type": "material",
		"display_name": "Plank",
		"value": 4,
	},
	"brick": { 
		"card": preload("res://Images/material_card.png"),
		"sprite": preload("res://Images/brick.png"),
		"card_type": "material",
		"display_name": "Brick",
		"value": 4,
	},
	"raw_meat": { 
		"card": preload("res://Images/food_card.png"),
		"sprite": preload("res://Images/raw_meat.png"),
		"card_type": "food",
		"display_name": "Raw Meat",
		"value": 1,
		"food_value": 1,
	},
	"cooked_meat": { 
		"card": preload("res://Images/food_card.png"),
		"sprite": preload("res://Images/cooked_meat.png"),
		"card_type": "food",
		"display_name": "Cooked Meat",
		"value": 1,
		"food_value": 2,
	},
	"bread": { 
		"card": preload("res://Images/food_card.png"),
		"sprite": preload("res://Images/bread.png"),
		"card_type": "food",
		"display_name": "Cooked Meat",
		"value": 1,
		"food_value": 2,
	},
	"house": {
		"card": preload("res://Images/building_card.png"),
		"sprite": preload("res://Images/house.png"),
		"card_type": "building",
		"display_name": "House",
		"value": 5,
		"stats": {"health": 25}
	},
	"cookhouse": {
		"card": preload("res://Images/building_card.png"),
		"sprite": preload("res://Images/cookhouse.png"),
		"card_type": "building",
		"display_name": "Cookhouse",
		"value": 5,
		"stats": {"health": 25}
	},
	"farm": {
		"card": preload("res://Images/building_card.png"),
		"sprite": preload("res://Images/farm.png"),
		"card_type": "building",
		"display_name": "Farm",
		"value": 5,
		"stats": {"health": 25}
	},
	"barn": {
		"card": preload("res://Images/building_card.png"),
		"sprite": preload("res://Images/barn.png"),
		"card_type": "building",
		"display_name": "Barn",
		"value": 5,
		"stats": {"health": 25}
	},
	"warehouse": {
		"card": preload("res://Images/building_card.png"),
		"sprite": preload("res://Images/warehouse.png"),
		"card_type": "building",
		"display_name": "Warehouse",
		"value": 5,
		"stats": {"health": 25}
	},
	"smeltery": {
		"card": preload("res://Images/building_card.png"),
		"sprite": preload("res://Images/smeltery.png"),
		"card_type": "building",
		"display_name": "Smeltery",
		"value": 5,
		"stats": {"health": 25}
	},
	"forge": {
		"card": preload("res://Images/building_card.png"),
		"sprite": preload("res://Images/forge.png"),
		"card_type": "building",
		"display_name": "Forge",
		"value": 5,
		"stats": {"health": 25}
	},
	"barracks": {
		"card": preload("res://Images/building_card.png"),
		"sprite": preload("res://Images/barracks.png"),
		"card_type": "building",
		"display_name": "Barracks",
		"value": 5,
		"stats": {"health": 25}
	},
	"well": {
		"card": preload("res://Images/building_card.png"),
		"sprite": preload("res://Images/well.png"),
		"card_type": "building",
		"display_name": "Well",
		"value": 5,
		"stats": {"health": 25}
	},
	"lumber_camp": {
		"card": preload("res://Images/building_card.png"),
		"sprite": preload("res://Images/lumber_camp.png"),
		"card_type": "building",
		"display_name": "Lumber Camp",
		"value": 5,
		"stats": {"health": 25}
	},
	"quarry": {
		"card": preload("res://Images/building_card.png"),
		"sprite": preload("res://Images/quarry.png"),
		"card_type": "building",
		"display_name": "Quarry",
		"value": 5,
		"stats": {"health": 25}
	},
	"iron_mine": {
		"card": preload("res://Images/building_card.png"),
		"sprite": preload("res://Images/iron_mine.png"),
		"card_type": "building",
		"display_name": "Iron Mine",
		"value": 5,
		"stats": {"health": 25}
	},
	"copper_mine": {
		"card": preload("res://Images/building_card.png"),
		"sprite": preload("res://Images/copper_mine.png"),
		"card_type": "building",
		"display_name": "Copper Mine",
		"value": 5,
		"stats": {"health": 25}
	},
	"gold_mine": {
		"card": preload("res://Images/building_card.png"),
		"sprite": preload("res://Images/gold_mine.png"),
		"card_type": "building",
		"display_name": "Gold Mine",
		"value": 5,
		"stats": {"health": 25}
	},
	"wooden_spear": {
		"card": preload("res://Images/equipment_card.png"),
		"sprite": preload("res://Images/wooden_spear.png"),
		"weapon_polygon": [
			Vector2(1, 0), Vector2(4, 3), Vector2(5, 8), Vector2(2, 11), Vector2(0, 11), Vector2(-3, 8), Vector2(-2, 3)
		],
		"polygon_offset": Vector2(-1, -17),
		"weapon_scale": Vector2(2, 2),
		"weapon_attack_sound": {"name": "spear_thrust", "volume_db": -14.0},
		"card_type": "equipment",
		"slot": "weapon",
		"weapon_type": "melee",
		"melee_type": "lunge",
		"display_name": "Wooden Spear",
		"value": 2,
		"description": "Basically a sharp stick.",
		"stats": {"add": {"attack": 1, "attack_range": 300, "attack_speed": 1.0}}
	},
	"bow": {
		"card": preload("res://Images/equipment_card.png"),
		"sprite": preload("res://Images/bow.png"),
		"sprite_rotation_offset": deg_to_rad(90),
		"weapon_scale": Vector2(2, 2),
		"card_type": "equipment",
		"slot": "weapon",
		"weapon_type": "ranged",
		"display_name": "Bow",
		"value": 2,
		"description": "A weak bow, with greater range than a wooden spear, but low attack speed.",
		"stats": {"add": {"attack": 1, "attack_range": 500, "attack_speed": 0.75}},
		"projectile_sprite": preload("res://Images/arrow.png"),
		"projectile_sound": {"name": "arrow", "volume_db": -14.0},
		"projectile_polygon": [Vector2(5, -4), Vector2(6, -4), Vector2(10, 0), Vector2(10, 1), Vector2(6, 5), Vector2(5, 5)],
		"projectile_speed": 1200.0,
		"projectile_lifetime": 0.5
	},
	"iron_spear": {
		"card": preload("res://Images/equipment_card.png"),
		"sprite": preload("res://Images/iron_spear.png"),
		"weapon_polygon": [
			Vector2(1, 0), Vector2(5, 4), Vector2(5, 8), Vector2(2, 12), Vector2(0, 12), Vector2(-3, 8), Vector2(-3, 4)
		],
		"polygon_offset": Vector2(-1, -17),
		"weapon_scale": Vector2(2, 2),
		"weapon_attack_sound": {"name": "spear_thrust", "volume_db": -14.0},
		"card_type": "equipment",
		"slot": "weapon",
		"weapon_type": "melee",
		"melee_type": "lunge",
		"display_name": "Iron Spear",
		"value": 3,
		"description": "A better, pointier spear.",
		"stats": {"add": {"attack": 2, "attack_range": 300, "attack_speed": 1.0}}
	},
	"iron_sword": {
		"card": preload("res://Images/equipment_card.png"),
		"sprite": preload("res://Images/iron_sword.png"),
		"weapon_polygon": [
			Vector2(1, 0), Vector2(-1, 2), Vector2(-1, 21), Vector2(3, 21), Vector2(3, 2)
		],
		"polygon_offset": Vector2(-1, -17),
		"weapon_scale": Vector2(2, 2),
		"weapon_attack_sound": {"name": "sword_slash", "volume_db": -14.0},
		"card_type": "equipment",
		"slot": "weapon",
		"weapon_type": "melee",
		"melee_type": "slash",
		"display_name": "Iron Sword",
		"value": 3,
		"description": "A basic iron sword.",
		"stats": {"add": {"attack": 2, "attack_range": 150, "attack_speed": 0.8}}
	},
	"iron_greatsword": {
		"card": preload("res://Images/equipment_card.png"),
		"sprite": preload("res://Images/iron_greatsword.png"),
		"weapon_polygon": [
			Vector2(1, 0), Vector2(-2, 3), Vector2(-2, 21), Vector2(4, 21), Vector2(4, 3)
		],
		"polygon_offset": Vector2(-1, -17),
		"weapon_scale": Vector2(3, 3),
		"weapon_attack_sound": {"name": "sword_slash", "volume_db": -14.0},
		"card_type": "equipment",
		"slot": "weapon",
		"weapon_type": "melee",
		"melee_type": "slash",
		"display_name": "Iron Greatsword",
		"value": 5,
		"description": "A large iron greatsword.",
		"stats": {"add": {"attack": 4, "attack_range": 200, "attack_speed": 0.6}}
	},
	"leather_helmet": {
		"card": preload("res://Images/equipment_card.png"),
		"sprite": preload("res://Images/leather_helmet.png"),
		"card_type": "equipment",
		"slot": "helmet",
		"display_name": "Leather Helmet",
		"value": 2,
		"description": "A poorly crafted leather helmet.",
		"stats": {"add": {"health": 2}}
	},
	"leather_chestplate": {
		"card": preload("res://Images/equipment_card.png"),
		"sprite": preload("res://Images/leather_chestplate.png"),
		"card_type": "equipment",
		"slot": "chestplate",
		"display_name": "Leather Chestplate",
		"value": 2,
		"description": "A poorly crafted leather chestplate.",
		"stats": {"add": {"health": 3, "armor": 1}}
	},
	"leather_leggings": {
		"card": preload("res://Images/equipment_card.png"),
		"sprite": preload("res://Images/leather_leggings.png"),
		"card_type": "equipment",
		"slot": "leggings",
		"display_name": "Leather Leggings",
		"value": 2,
		"description": "A poorly crafted leather leggings.",
		"stats": {"add": {"health": 3}}
	},
	"leather_boots": {
		"card": preload("res://Images/equipment_card.png"),
		"sprite": preload("res://Images/leather_boots.png"),
		"card_type": "equipment",
		"slot": "boots",
		"display_name": "Leather Boots",
		"value": 2,
		"description": "A poorly crafted leather boots.",
		"stats": {"add": {"health": 1}}
	},
	"peasant": {
		"card": preload("res://Images/unit_card.png"),
		"sprite": preload("res://Animations/peasant.tres"),
		"animated": true,
		"card_type": "unit",
		"display_name": "Peasant",
		"stats": {"health": 10, "attack": 0, "armor": 0, "attack_speed": 0.0, "attack_range": 0},
		"food_required": 2,
	},
	"baby_peasant": {
		"card": preload("res://Images/unit_card.png"),
		"sprite": preload("res://Images/baby_peasant.png"),
		"card_type": "unit",
		"display_name": "Baby Peasant",
		"stats": {"health": 3},
		"food_required": 2,
	},
	"wolf": {
		"card": preload("res://Images/enemy_card.png"),
		"sprite": preload("res://Images/wolf.png"),
		"card_type": "enemy",
		"display_name": "Wolf",
		"stats": {"health": 5, "attack": 0, "armor": 0, "attack_speed": 0.0, "attack_range": 0},
		"min_jump_time": 1.5,
		"max_jump_time": 2.5,
		"jump_distance": 150.0,
		"raid_value": 1,
		"raid_group_range": Vector2(3, 6),
		"weapons": [
			{
				"name": "wolf_claw",
				"sprite": preload("res://Images/wolf_claw.png"),
				"weapon_polygon": [Vector2(-2,12), Vector2(-5,15), Vector2(-3,22), Vector2(0,19)],
				"polygon_offset": Vector2(-1,-17),
				"weapon_scale": Vector2(2,2),
				"weapon_attack_sound": {"name": "claw_slash", "volume_db": -10.0},
				"slot": "weapon",
				"weapon_type": "melee",
				"melee_type": "slash",
				"weapon_stats": {"add": {"attack": 1, "attack_range": 150, "attack_speed": 0.75}},
				"display_name": "Wolf Claw"
			},
			{
				"name": "wolf_claw_2",
				"sprite": preload("res://Images/wolf_claw.png"),
				"weapon_polygon": [Vector2(-2,12), Vector2(-5,15), Vector2(-3,22), Vector2(0,19)],
				"polygon_offset": Vector2(-1,-17),
				"weapon_scale": Vector2(2,2),
				"weapon_attack_sound": {"name": "claw_slash", "volume_db": -10.0},
				"slot": "weapon",
				"weapon_type": "melee",
				"melee_type": "slash",
				"weapon_stats": {"add": {"attack": 1, "attack_range": 150, "attack_speed": 0.75}},
				"display_name": "Wolf Claw"
			}
		],
		"loot_table": [
			{"subtype": "leather", "chance": 0.7},
			{"subtype": "raw_meat", "chance": 0.5}
		]
	},
	"horse": {
		"card": preload("res://Images/neutral_card.png"),
		"sprite": preload("res://Images/horse.png"),
		"card_type": "neutral",
		"display_name": "Horse",
		"stats": {"health": 5},
		"min_jump_time": 2.0,
		"max_jump_time": 3.0,
		"jump_distance": 250.0,
		"loot_table": [
			{ "subtype": "leather", "chance": 0.9 },
			{ "subtype": "leather", "chance": 0.5 },
			{ "subtype": "raw_meat", "chance": 0.9 },
		]
	},
	"cow": {
		"card": preload("res://Images/neutral_card.png"),
		"sprite": preload("res://Images/cow.png"),
		"card_type": "neutral",
		"display_name": "Cow",
		"stats": {"health": 4},
		"min_jump_time": 2.0,
		"max_jump_time": 3.0,
		"jump_distance": 125.0,
		"loot_table": [
			{ "subtype": "leather", "chance": 0.9 },
			{ "subtype": "leather", "chance": 0.5 },
			{ "subtype": "raw_meat", "chance": 0.9 },
			{ "subtype": "raw_meat", "chance": 0.3 },
		]
	},
	"rabbit": {
		"card": preload("res://Images/neutral_card.png"),
		"sprite": preload("res://Images/rabbit.png"),
		"card_type": "neutral",
		"display_name": "Rabbit",
		"stats": {"health": 3},
		"min_jump_time": 1.5,
		"max_jump_time": 2.5,
		"jump_distance": 150.0,
		"loot_table": [
			{ "subtype": "leather", "chance": 0.5 },
			{ "subtype": "raw_meat", "chance": 0.5 },
		]
	},
	"chicken": {
		"card": preload("res://Images/neutral_card.png"),
		"sprite": preload("res://Images/chicken.png"),
		"card_type": "neutral",
		"display_name": "Chicken",
		"stats": {"health": 2},
		"min_jump_time": 2.0,
		"max_jump_time": 3.0,
		"jump_distance": 175.0,
		"loot_table": [
			{ "subtype": "raw_meat", "chance": 0.5 },
			{ "subtype": "raw_meat", "chance": 0.1 },
		]
	},
}
